### ISSUE TITLE
interpolation-super-power-cb-gh-000 doesn't have any Rspec files.

### ISSUE THREAD

**Issue by MikeHa** [learn-co-curriculum/interpolation-super-power#17]
I am attempting to run the learn command, but this folder doesn't have any other files including Rspec files.  I clicked Open on the Curriculum page, but there is only the lib folder inside with display_rainbow.rb

So I ended up with a message
`You don't appear to be in a Learn lesson's directory. Please cd to an appropriate directory and try again.`
When I try to send the learn command.

**Comment by cjbrock** [comment]
Hi @michael-h-nguyen! There could be a lot of different reasons that you would be experiencing behavior like this.  If you're still having issues with this lab, please contact our Technical Coaches using the Ask A Question button, and they can work with you to help you figure it out. 
Thank you! --Corinna
