### ISSUE TITLE
Error when output is correct?

### ISSUE THREAD

**Issue by o-psi** [learn-co-curriculum/interpolation-super-power#18]
```
def display_rainbow(colors)

  str = ""
  colors_and_first_letter = []

  colors.each{|i|
    first_letter = i[0,1].upcase
    colors_and_first_letter.insert(-1, "#{first_letter}: #{i}")
  }

  str = colors_and_first_letter.join(", ")
  puts"#{str}"

end
```

**gets error** 

```
 Failure/Error: expect(colors).to receive(:[]).with(0).at_least(:once).and_return("red")
       (["red", "orange", "yellow", "green", "blue", "indigo", "violet"]).[](0)
           expected: at least 1 time with arguments: (0)
           received: 0 times
     # ./spec/display_rainbow_spec.rb:14:in `block (2 levels) in <top (required)>'
Finished in 0.0745 seconds (files took 0.32655 seconds to load)
2 examples, 1 failure
Failed examples:
rspec ./spec/display_rainbow_spec.rb:11 # #display_rainbow prints out the colors of the rainbow correctly when passed in in order

```

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙

**Comment by TyJaYo** [comment]
@gj The curriculum problem @o-psi brings up here is that the lesson doesn't say anything like "you have to call each element in the array by index number or the test will fail". I had a similar issue. I completed this exercise 3 different ways before I realized the test was actually punishing me for **not** repeating myself.

The last bit of the instructions make it seem like you have the **option** to do it the beginner way (interpolate each reference by index) or the advanced way (loops, getting first char, etc.). 

In my opinion the test should be rewritten (or maybe the whole exercise), but the quick fix would be to make it clear in the instructions that the test will expect you to write out the same interpolation six times.

**Comment by gj** [comment]
Thoughtful comment @TyJaYo !

Reopening this for our curriculum team to see.

**Comment by cjbrock** [comment]
Thanks @o-psi and @TyJaYo! I've updated the README to indicate that you shouldn't use loops as a quick fix for now, and we'll add it to our backlog to refactor the tests to account for both possibilities in the future.
// <3 Corinna
