### ISSUE TITLE
Unclear Desired Outcome

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/interpolation-super-power#21]
Hey there, 

I wanted to draw your attention to this lab. I was having a difficult time with the lab so I consulted one of the technical coaches. 

After working with the technical coach, I found the error with my code, but the following code is what my technical coach suggested was correct: 

```
`def display_rainbow(colors)
puts "R: #{colors[0]}, O: #{colors[1]}, Y: #{colors[2]}, G: #{colors[3]}, B: #{colors[4]}, I: #{colors[5]}, V: #{colors[6]}"
end`
```
     
While this code runs the "learn" function without error, it does not produce, what I believed to be the expected output of: "R: red, O: orange, Y: yellow, G: green, B: blue, I: indigo, V: violet". 

With little issue I changed my code to run correctly, writing: 

```
`colors = ["red", "orange", "yellow", "green", "blue", "indigo", "purple"]

def display_rainbow(colors)
puts "R: #{colors[0]}, O: #{colors[1]}, Y: #{colors[2]}, G: #{colors[3]}, B: #{colors[4]}, I: #{colors[5]}, V: # 
{colors[6]}"
end

display_rainbow(colors)`
```

I think this lab could benefit from being more direct about the desired code for the exercise--is it enough to post only the method, or is the desired outcome the output: "R: red, O: orange, Y: yellow, G: green, B: blue, I: indigo, V: violet"? If it is the latter, my technical coach was not on the same page, and when I continued to ask her why the array was not necessary for the lab, she failed to provide me with an answer I could understand as a beginner coder.

**Comment by cjbrock** [comment]
Thank you for your feedback! We'll rewrite the lab to be a little more clear as to what the expected outcome is. 

// <3 Corinna
