### ISSUE TITLE
OAuth token a second time

### ISSUE THREAD

**Issue by m-gamao** [learn-co-curriculum/interpolation-super-power#23]
Hi, I ran into this issue a few weeks ago, and it hasn't happened again until today.  Can you tell me why it happens?  Thanks.

courageous-program-2331@cdad0abbc98e:~$ learn open interpolation-super-power-v-000
chmod: cannot access '/home/courageous-program-2331/.netrc': No such file or directory
Connecting to Learn...
To connect with the Learn web application, you will need to configure
the Learn gem with an OAuth token. You can find yours at the bottom of your profile
page at: https://learn.co/your-github-username.

Once you have it, please come back here and paste it in: chmod: cannot access '/home/courageous-program-2331/.netrc': No such file or directory
^C/usr/local/rvm/gems/ruby-2.3.1/gems/learn-config-1.0.77/lib/learn_config/cli.rb:27:in `gets': Interrupt
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-config-1.0.77/lib/learn_config/cli.rb:27:in `gets'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-config-1.0.77/lib/learn_config/cli.rb:27:in `ask_for_oauth_token'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-config-1.0.77/lib/learn_config/setup.rb:221:in `setup_learn_config_machine'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-config-1.0.77/lib/learn_config/setup.rb:145:in `setup_netrc'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-config-1.0.77/lib/learn_config/setup.rb:38:in `check_config'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-config-1.0.77/lib/learn_config/setup.rb:30:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-config-1.0.77/lib/learn_config/setup.rb:6:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-config-1.0.77/bin/learn-config:15:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-config:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-config:23:in `<main>'

**Comment by drakeltheryuujin** [comment]
Hi @guerilla17! 
[Raising issues on GitHub][raise] should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.). If Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try
to discern a proper path to resolution.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
