### ISSUE TITLE
confusing example: ROYGBIV

### ISSUE THREAD

**Issue by nicolefederici** [learn-co-curriculum/interpolation-super-power#3]
I found it confusing to automate something that would be easier just to puts. It would have made more sense to me if the little machine was doing something for me that reduced my own effort.

**Comment by AnnJohn** [comment]
Thanks @nicolefederici for raising this issue. We're going to keep the lesson as is for now, but definitely think your input is great. When we do a full curriculum review, we'll fix up this lesson. Thanks again!
