### ISSUE TITLE
Should the "R" in "R: red" be hardcoded or programmatically determined?

### ISSUE THREAD

**Issue by abhishekpillai** [learn-co-curriculum/interpolation-super-power#4]
I have encountered a couple users who are able to correctly interpolate #{colors[0]} but are not sure how to programmatically get the first letter of the color and capitalize. For this lab, is the intention that they would achieve the programmatic or the hardcoded solution?

As a learn expert, which should we guide a user towards?

Here is an example question: https://learn.co/lessons/13394/?question_uid=q-45e3b450-a8d8-4463-9853-7502bf693121&batch_id=286&track_id=12307

**Comment by AnnJohn** [comment]
@loganhasson can you take a look at this when you get a chance? Thanks

**Comment by aturkewi** [comment]
Updated instruction in PR #7
