### ISSUE TITLE
Wording could be better in instructions?

### ISSUE THREAD

**Issue by sarahparmenter** [learn-co-curriculum/interpolation-super-power#5]
colors will be passed in as: ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet']
# display_rainbow should print out the colors of the rainbow in the following format: "R: red, O: orange, Y: yellow, G: green, B: blue, I: indigo, V: violet"

This section had me in a loop for hours. I was initially coding - 
def display_rainbow (red = "R:red", orange = "O: orange" and so on) 
and then trying to print it here individually. 

It turned out the solution was to use the R: in the puts and just call the colour. I made this horrendously more difficult for myself because I think it's the first time we've been asked to "accept an array using the colours as an argument" - in that language. For a newbie like me. I found this lesson exceptionally confusing. It was the only lesson in the whole programme I've struggled with and had to spend a few hours on before biting the bullet and looking at the community solutions. 

I think it's in the wording of the instructions. Just as your brain is doing little mental ticks on everything we've learned so far as you read down it, the "colors will be passed" section added on at the bottom seems like an after thought to throw you off.

**Comment by AnnJohn** [comment]
thanks @sarahparmenter for the detailed issue. We'll review this as soon as we can and update.

**Comment by aturkewi** [comment]
Updated instruction in PR #7
