### ISSUE TITLE
display_rainbow_spec.rb causing errors when passed empty array

### ISSUE THREAD

**Issue by spadafiva** [learn-co-curriculum/interpolation-super-power#8]
When running #display_rainbow the rspec tests fail when passed an empty array, but there are no directions to either edit the tests or to deal with an empty array.  Putting a default case in the method arguments still causes there to be an issue.  

This could be fixed by modifiying the tests:
describe '#display_rainbow' do
  it 'accepts one argument' do
    allow(self).to receive(:puts)
    colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet']

```
expect { display_rainbow(colors) }.to_not raise_error(NoMethodError)
expect { display_rainbow(colors) }.to_not raise_error(ArgumentError)
```

  end

  it 'prints out the colors of the rainbow correctly when passed in in order' do
    colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet']

```
expect(colors).to receive(:[]).with(0).at_least(:once).and_return("red")
expect(colors).to receive(:[]).with(1).at_least(:once).and_return("orange")
expect(colors).to receive(:[]).with(2).at_least(:once).and_return("yellow")
expect(colors).to receive(:[]).with(3).at_least(:once).and_return("green")
expect(colors).to receive(:[]).with(4).at_least(:once).and_return("blue")
expect(colors).to receive(:[]).with(5).at_least(:once).and_return("indigo")
expect(colors).to receive(:[]).with(6).at_least(:once).and_return("violet")

expect { display_rainbow(colors) }.to output("R: red, O: orange, Y: yellow, G: green, B: blue, I: indigo, V: violet\n").to_stdout
```

  end
end

OR

Alternatively, I did this in my code:
def display_rainbow(colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet'])
  if not colors.any? 
    colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet']
  end
  puts  "#{colors[0][0].upcase}: #{colors[0]}, #{colors[1][0].upcase}: #{colors[1]}, #{colors[2][0].upcase}: #{colors[2]}, #{colors[3][0].upcase}: #{colors[3]}, #{colors[4][0].upcase}: #{colors[4]}, #{colors[5][0].upcase}: #{colors[5]}, #{colors[6][0].upcase}: #{colors[6]}" 

end
display_rainbow(['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet'])

**Comment by AnnJohn** [comment]
thanks @spadafiva for raising this. we'll look into it very soon.

**Comment by aturkewi** [comment]
This should have been closed with the PR noted above ^
